### ISSUE TITLE
Code Gen Discussion

### ISSUE THREAD

**Issue by IrishBruse** [NotNotTech/Raylib-CsLo#12]
![image](https://user-images.githubusercontent.com/14964651/156936076-6e76824d-b44f-4ad5-ab04-1bfbe8392ef6.png)
So in the raylib json definition file it has parameters with the alias types should I Convert them to their base type?

**Comment by jasonswearingen** [comment]
If you mean `RenderTexture`, I think maybe okay to leave it as `RenderTexture2D` and add a global using alias: `global using RenderTexture2D = Raylib_CsLo.RenderTexture;`

There are other `global using` aliases to consider, you can see a listing here https://github.com/NotNotTech/Raylib-CsLo#known-issues

**Comment by IrishBruse** [comment]
Im wondering if we add the global usings does it get exported to the nuget package?
it would be nice to have the method parameter to match the cheatsheet as much as possible.

**Comment by IrishBruse** [comment]
![image](https://user-images.githubusercontent.com/14964651/156939450-557ecd62-0a75-467b-8d3f-d6924d51e619.png)
how would you go about making a safe version of this I assume it would be some form of
`Action<int, string, params object[] args>`
Didnt you say you were working on something relating to logging

**Comment by jasonswearingen** [comment]
Yes the main problem is the usage of variable length arguments on the C api side.     I haven't figured out a good way to solve that from C#, though I suppose it exists.

There is an alternate, proven solution though:  do something similar to what Raylib-CS does, however I don't like their solution much because I think it's a lot more complex than it needs to be (around `sprintf` calls for various OS).   Also I think there is a buffer exploit risk with the sprintf they are using.   

I don't need this log interception and think it's pretty low priority so I didn't bother investigating further.

**Comment by jasonswearingen** [comment]
I did a couple checkins to fix+pretty up your new example picker (your example picker is pretty awesome btw!)

I was then working on troubleshooting the MeshInstancing example:

## Your `RayMath` codegen now calls the native raylib raymath.  
The old clangsharp version actually emits C# code that does all the `raymath` and `easings` code.   This C# "auto port" is a bit more performant, because it doesn't have to marshall across native/managed code boundaries.   However, there is a serious logic difference with `raymath` as well.    OpenGL+Raylib uses column major matricies, while DotNet uses row-major matricies.  This means that if you mix matrix computations between the two domains you will get corrupted results.  

Specifically, the line 65 in `MeshInstancing.cs`
```cs
translations[i] = MatrixTranslate(x, y, z);
```
is now returning a column major matrix, while in the clangsharp version it's returning a row-major matrix.   

When I did the initial port I found this "C# codegen" to be a feature, and it helped keep all matrix computations in "C# land" and only need to Transpose the final matrix before passing to raylib.     Using the native raymath will be (slightly) slow, and will require more careful matrix interop.

To solve this problem for the example, I checked in a solution on line 235 of MeshInstancing.cs which is simply 

```cs
            ////DrawMesh(cube, material, MatrixIdentity());
            //for (int i = 0; i < transforms.Length; i++)
            //{
            //    //flip for opengl column major
            //    transforms[i] = Matrix4x4.Transpose(transforms[i]);
            //}
            DrawMeshInstanced(cube, material, transforms, MAX_INSTANCES);
```

But the "real" solution should be one of the two:
1) port the raymath+easing to C# code (so matrix math stays row-major)
2) keep Raylib/OpenGL matrix explicitly seperate from DotNet.   Rename the raylib's Matrix struct to be `GL_Matrix` or something similar.  and can offer simple conversion methods (can also use operator overrides to help provide automatic conversion)

**Comment by jasonswearingen** [comment]
Physac bug.   line 72 of Physac.cs
```
    /// <summary> Returns a physics body of the bodies pool at a specific index </summary>
    [DllImport("raylib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    public static extern PhysicsBodyData GetPhysicsBody(int index);
```

The line should instead return a pointer:
```cs
public static extern PhysicsBodyData* GetPhysicsBody(int index);
```

This is why the physac examples are all broken.  The `PhysicsBodyData()` is stored in native memory, so C# needs a pointer to it.  Other physics functions such as `CreatePhysicsBodyRectangle()` also need to return a pointer.

**Comment by jasonswearingen** [comment]
closing, please ping me if you want to reopen irishbruise!
