### ISSUE TITLE
[v4.2] Build Raylib native binaries for OSX

### ISSUE THREAD

**Issue by jasonswearingen** [NotNotTech/Raylib-CsLo#23]
Raylib-CsLo bundles a custom version of the Raylib native binary: it's compiled to include extras such as `raygui`,`physac`, and `easings`.

However `Raylib 4.2` changes it's project structures.   I was able to build the **windows x64** binaries properly, but was unable to build either the **linux** or **osx** binaries.

as building native binaries on various platforms is not my area of expertise, I ask for help here.

In the meantime, the Raylib-CsLo 4.2 version is on Nuget as a pre-release, Win_x64 only build.    The release version of CsLo's nuget package will remain 4.0 until this issue is resolved.

## If you are interested in helping
See the https://github.com/NotNotTech/Raylib-CsLo/tree/main/sub-modules folder's readme for the current (broken) workflow for building linux.

When I followed the linux steps (Ubuntu 22.04 x64) This is the error I received when calling make:
> Creating bin/Release.DLL
> Linking raylib
> /usr/bin/ld: obj/x64/Release.DLL/rtextures.o: relocation R_X86_64_TPOFF32 against `stbi__g_failure_reason' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: failed to set dynamic section sizes: bad value
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:117: bin/Release.DLL/raylib.dll] Error 1
> make: *** [Makefile:36: raylib] Error 2

It seems to be something about the `.so `failing to build.

**Comment by jasonswearingen** [comment]
Peter0x44 on Raylib Discord showed me how to build linux binaries, so that's taken care of.   If you know how to build osx binaries and/or setup github actions, help is still appreciated!

**Comment by CodingMadness** [comment]
[FONT_TEST_RAYLIBCS.zip](https://github.com/NotNotTech/Raylib-CsLo/files/9621457/FONT_TEST_RAYLIBCS.zip)

This is my MacOsx project. Can you run it? DO u have a mac? If so, just extract the project,open the .sln and click run and u will see the exception.

Macosx: 10.15.7 catalina 
xcode 10

**Comment by CodingMadness** [comment]
[osx.zip](https://github.com/NotNotTech/Raylib-CsLo/files/9625650/osx.zip)
@jasonswearingen 
These are files compiled with .net 6.0 and I generally would highly advise you, especially since you write extracode for performance anyway tocompile against .net6! its insane improvements over the cpl of years and i think the end user will more benefit from this and u dont have to do nothing extra! just set the target to .net6 and click "build"

**Comment by jasonswearingen** [comment]
sorry I can't build/run osx:  I don't have a mac.   

Also FYI You can run raylib-cslo in net6 no problem.  I don't have to build targeting net6.   targeting `net-standard-2.1` lets various platforms use raylib-cslo.   If I built it net6 it is excluding a lot of other platforms with no benefit.

**Comment by CodingMadness** [comment]
I am wondering what more platforms you wann support with .netstandard, .net 6 and greater supports everything in the .net ecosystem , is incredibly fast /more performant aswell as just the thing which is now and should be used everything .net related. Idk which platforms u will get with .netstandard since it can aswell only be used within the .net ecosystem and who the hell still useses .net framework, outside of some companies who are still not changing cause their entire codebase is on .net framework 4.8 orso..

**Comment by jasonswearingen** [comment]
This is done and verified works on Mac x64.   Thanks Shpendicus!
