### ISSUE TITLE
Change-Request: Put all Colors in "Color" struct

### ISSUE THREAD

**Issue by CodingMadness** [NotNotTech/Raylib-CsLo#24]
Title.

Its bit more clearer and semantically correct to say "Color.WHITE" then "Raylib.WHITE" or even when "using static Raylib"; "WHITE"

IMHO. 

Atleast think about it, nothing big of a complain here just some small hint.

Cheers nd thx for doing work to perma upgrade raylib man!

**Comment by jasonswearingen** [comment]
You are right that it would be nicer, and more correct.   

However the `CsLo` bindings are auto-generated from the Raylib native code's api signature.  In the native code there is no `Color` struct, all the colors just hang off of the base raylib class.    

I don't want `CsLo` to have custom wrappers for things inside raylib, because it's the route that `raylib-cs` went, and I strongly feel that it's a flawed approach from an upgradeability standpoint.  (I always poke fun at them, saying they have an "artisanal, bespoke wrapper", where I have a "cold, calculating robo-wrapper".   I should put that in the readme 🗡️ 


If you really, really, REALLY feel like this is needed, you can submit a PR to https://github.com/NotNotTech/Raylib-Extras-CsLo  But really I think just accept it for the cold, calculating thing that it is!

**Comment by CodingMadness** [comment]
Understood and I can live with it, if its that big of a hassel to change, then screw it.. :D

**Comment by jasonswearingen** [comment]
okay will close!
