### ISSUE TITLE
SIGSEGV code 139 when caling DrawTextEx

### ISSUE THREAD

**Issue by CodingMadness** [NotNotTech/Raylib-CsLo#25]
Title.

calling this code with the empty string ""here WORKS: 
`Raylib.DrawTextEx(logText.Src, "", new Vector2(pos.X, pos.Y) * 1.2f, logText.Size, 1f, Raylib.RED);`

But this FAILS:
` Raylib.DrawTextEx(logText.Src, "A", new Vector2(pos.X, pos.Y) * 1.2f, logText.Size, 1f, Raylib.RED);`

Dont mind variable "LogText" its just my custom struct either way its used in both of the above and it works in one of it.

**Comment by jasonswearingen** [comment]
I would suggest you look at the examples, and see what you may be doing differently, because I have verified that all the samples work.

Just eyeballing your code, are you sure that `logText.Src` and `logText.Size` are valid?   if they were not, it would not be surprising that an empty string "prints" but an actual string crashes.

**Comment by CodingMadness** [comment]
@jasonswearingen 
I dont know what this kind of black magic halluzination was but its indeed gone, i swear to god... when i used it as I did above RIder gave me a freaking Sigsegv ....... idk.. i will test on next potential occurences more precisely if i am not doing smth bad there.. My appologize!

**Comment by jasonswearingen** [comment]
will close this, feel free to ping me/reopen if needed!
