### ISSUE TITLE
Is Raylib / raylib_clso working on Mac M1 2020? 

### ISSUE THREAD

**Issue by aslamna9** [NotNotTech/Raylib-CsLo#28]

**Comment by jasonswearingen** [comment]
Not working, because we do not have a native raylib built for m1.  I don't have a mac (nor M1) so if you are interested in getting the native raylib library built for m1, you can send it to me to integrate into cslo.

**Comment by atsuzaki** [comment]
@jasonswearingen I have a M1 mac and I'm wanting to build a dylib for it. Would you mind sharing more detailed pointers on how to build the dylibs? (Happy to keep building it too)

~~I'm not experienced enough with dotnet build process to figure out how to do it from the resources you had in the runtimes folder, unfortunately.~~
Nevermind I was stupid and did not realize that it was supposed to be, like, base raylib. I was able to build them, but strangely enough I needed the library plus the generated symlinks for this library to recognize it? (I needed three files: libraylib.dylib, and it's symlinks: libraylib.4.2.0.dylib, libraylib.420.dylib in the folder for it to work)

**Comment by atsuzaki** [comment]
Also I learned from https://github.com/ChrisDill/Raylib-cs/issues/127#issuecomment-1236128795 that the official release provides an universal x64+arm64 dylib now so I think taking that build (plus perhaps some config change?) would enable M1 support.

**Comment by leftbones** [comment]
Any progress on this?

**Comment by jasonswearingen** [comment]
someone sent me osx arm64 binaries.  give  me a few minutes and i'll try to get it checked in.

**Comment by jasonswearingen** [comment]
ok new version 4.2.0.4 should support Mac M1.  let me know if it works (or not)
https://www.nuget.org/packages/Raylib-CsLo

**Comment by leftbones** [comment]
> ok new version 4.2.0.4 should support Mac M1. let me know if it works (or not) https://www.nuget.org/packages/Raylib-CsLo

Still getting a massive error message when trying to compile:
`"Unable to load shared library 'raylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: \ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib.dylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib.dylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib.dylib' (no such file)\ndlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib.dylib' (no such file)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib.dylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib.dylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib.dylib' (no such file)\ndlopen(raylib.dylib, 0x0001): tried: 'raylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSraylib.dylib' (no such file), '/usr/lib/raylib.dylib' (no such file, not in dyld cache), 'raylib.dylib' (no such file), '/usr/local/lib/raylib.dylib' (no such file), '/usr/lib/raylib.dylib' (no such file, not in dyld cache)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib.dylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib.dylib' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib.dylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib.dylib' (not a mach-o file)\ndlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib.dylib' (no such file)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib.dylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib.dylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib.dylib' (no such file)\ndlopen(libraylib.dylib, 0x0001): tried: 'libraylib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibraylib.dylib' (no such file), '/usr/lib/libraylib.dylib' (no such file, not in dyld cache), 'libraylib.dylib' (no such file), '/usr/local/lib/libraylib.dylib' (no such file), '/usr/lib/libraylib.dylib' (no such file, not in dyld cache)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/raylib' (no such file)\ndlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib' (no such file)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/raylib' (no such file)\ndlopen(raylib, 0x0001): tried: 'raylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSraylib' (no such file), '/usr/lib/raylib' (no such file, not in dyld cache), 'raylib' (no such file), '/usr/local/lib/raylib' (no such file), '/usr/lib/raylib' (no such file, not in dyld cache)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/runtimes/osx-arm64/native/libraylib' (no such file)\ndlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib' (no such file)\ndlopen(/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib, 0x0001): tried: '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib' (no such file), '/Users/evan/Documents/GitHub/DungeonsOfMyriad/bin/Debug/net7.0/libraylib' (no such file)\ndlopen(libraylib, 0x0001): tried: 'libraylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibraylib' (no such file), '/usr/lib/libraylib' (no such file, not in dyld cache), 'libraylib' (no such file), '/usr/local/lib/libraylib' (no such file), '/usr/lib/libraylib' (no such file, not in dyld cache)\n"`

**Comment by jasonswearingen** [comment]
looks like you need a `raylib.dylib` file so i'll try checking that in tomorrow (about 12hrs from now)

**Comment by jasonswearingen** [comment]
try out `4.2.0.5-alpha1` https://www.nuget.org/packages/Raylib-CsLo/4.2.0.5-alpha1

However from the error log posted above, I see that it finds the symlink file, but shows the error `(not a mach-o file)` so I am not sure this will work.

If the  `4.2.0.5-alpha1` works let me know.  **If not, the solution to this error is simple.**  This needs someone on a Mac M1 to download this repository and build the native binaries, and either send them to me or submit a PR.  Instructions can be found here https://github.com/NotNotTech/Raylib-CsLo/tree/main/sub-modules

I don't own a mac m1 so I can not do this.

**Comment by leftbones** [comment]
Hey, sorry I didn't get around to testing this sooner. Just installed `4.2.0.5-alpha1` and everything seems to be working fine! Thanks a ton for helping out with this! I'm pretty new to C# still and until now had only been working from my PC.

**Comment by jasonswearingen** [comment]
thank you for the followup.   i'll try to publish `4.2.0.5` later today.

**Comment by leftbones** [comment]
One thing I just noticed, might be unrelated, but if I add `ToggleFullscreen()` the game never launches. Successful build, no errors, but the window never opens and nothing happens at all. The code I'm testing with on my Mac is a month old version of my project, so when I'm back at my PC I'll get the latest known-working stuff and do more testing.

**Comment by leftbones** [comment]
Okay, it must have been something with my old code. Tested the latest version of my project and `ToggleFullscreen()` works as expected. Thanks for getting this working so quickly!

**Comment by jasonswearingen** [comment]
okay glad it's working, the `4.2.0.5` is published on nuget now.
